services:
  floci-prd:
    image: floci/floci:latest
    container_name: floci-prd
    ports:
      - "4568:4566"
    user: root
    environment:
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - floci-data-prd:/app/data

volumes:
  floci-data-prd:
